In [1]:
import numpy as np

In [2]:
arr = np.arange(64) + 1
arr = np.reshape(arr, (8, 8))
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [3]:
np.linalg.det(arr)

0.0

In [9]:
np.linalg.eig(arr.T)[0] == np.linalg.eig(arr)[0]

array([False, False, False, False, False, False, False, False])

In [10]:
np.linalg.eig(arr)[0]

array([ 2.69957136e+02+0.00000000e+00j, -9.95713630e+00+0.00000000e+00j,
       -9.31244401e-15+0.00000000e+00j,  7.67873015e-15+0.00000000e+00j,
        1.62946388e-15+3.93672787e-15j,  1.62946388e-15-3.93672787e-15j,
       -1.33221286e-15+0.00000000e+00j,  7.41776564e-16+0.00000000e+00j])

In [11]:
np.linalg.eig(arr.T)[0]

array([ 2.69957136e+02+0.00000000e+00j, -9.95713630e+00+0.00000000e+00j,
       -6.93383542e-15+0.00000000e+00j,  2.42585470e-15+4.39348593e-15j,
        2.42585470e-15-4.39348593e-15j, -6.42084121e-16+2.41685027e-15j,
       -6.42084121e-16-2.41685027e-15j,  3.11803686e-15+0.00000000e+00j])

In [15]:
np.linalg.eig(arr)[1][0]

array([-5.28890798e-02+0.j        ,  5.62772435e-01+0.j        ,
       -1.04942896e-01+0.j        , -2.57337609e-01+0.j        ,
        9.07024387e-03-0.02869221j,  9.07024387e-03+0.02869221j,
       -7.36184709e-02+0.j        , -4.50470195e-04+0.j        ])

In [16]:
w = np.linalg.eig(arr)[0]

v = np.linalg.eig(arr)[1]

In [17]:
np.sum((v.T * v) * w)

(14.171701187702007-0.7341008018374734j)

In [26]:
((v.T * v) * w)

array([[ 7.55138884e-01+0.00000000e+00j,  7.09093888e-01-0.00000000e+00j,
        -1.95646472e-16+0.00000000e+00j,  5.41133539e-16+0.00000000e+00j,
        -4.43875955e-17+3.83845841e-18j, -5.37955736e-17-4.65202202e-18j,
        -4.85286966e-17+0.00000000e+00j,  1.89950957e-19+0.00000000e+00j],
       [-1.92249006e+01+0.00000000e+00j, -1.66420301e+00+0.00000000e+00j,
         5.25816469e-16-0.00000000e+00j,  2.03870205e-16+0.00000000e+00j,
         1.87431280e-17-1.77629778e-17j,  7.31625630e-17+6.93366115e-17j,
         9.15221552e-18-0.00000000e+00j, -3.03711831e-17+0.00000000e+00j],
       [ 5.67156821e+00+0.00000000e+00j,  5.62218280e-01-0.00000000e+00j,
        -6.35093310e-16+0.00000000e+00j, -7.25757688e-17+0.00000000e+00j,
        -9.43810046e-17-2.37558749e-17j,  3.14694298e-16-7.92091419e-17j,
         3.90769541e-16-0.00000000e+00j, -7.44767613e-17+0.00000000e+00j],
       [ 1.90243514e+01+0.00000000e+00j, -2.64361865e-01+0.00000000e+00j,
         8.80168687e-17-0.00000000e

In [27]:
w

array([ 2.69957136e+02+0.00000000e+00j, -9.95713630e+00+0.00000000e+00j,
       -9.31244401e-15+0.00000000e+00j,  7.67873015e-15+0.00000000e+00j,
        1.62946388e-15+3.93672787e-15j,  1.62946388e-15-3.93672787e-15j,
       -1.33221286e-15+0.00000000e+00j,  7.41776564e-16+0.00000000e+00j])

In [24]:
np.outer(v, v.T).shape

(64, 64)

In [25]:
v.shape

(8, 8)

In [36]:
np.linalg.inv(v) * v * w

array([[ 4.96565296e+00-3.40387840e-16j,  2.01330659e+00-8.55766761e-17j,
        -3.62360936e-16-4.27329787e-33j,  7.55407721e-16-6.96688807e-33j,
        -5.02994219e-17+4.34968906e-18j, -5.17682479e-17-4.47670715e-18j,
        -4.08762758e-17-3.08016126e-33j,  1.43110028e-19-4.81505767e-36j],
       [-2.41756813e+01+3.07884182e-15j, -2.27365554e+00-4.33415065e-17j,
         8.44572910e-16+4.13108272e-32j,  5.25656111e-16+9.60510095e-32j,
        -3.92616971e-17+3.72085521e-17j,  1.34639014e-17+1.27598223e-17j,
         4.74816650e-18-1.01848824e-33j, -1.98437571e-17-6.40422519e-34j],
       [ 1.69035025e+01-1.56685168e-14j,  2.61107482e+00-4.04150244e-17j,
        -2.69065974e-15-1.73793665e-31j,  8.53564934e-16-4.43017937e-31j,
         2.30686319e-16+5.80641769e-17j, -6.42698800e-17+1.61768487e-17j,
         1.40759011e-16-1.57202634e-31j, -7.13268339e-17-2.57248251e-33j],
       [ 1.49685334e+02+2.01324195e-14j, -1.54564273e+00-2.34185300e-17j,
         2.86755059e-16+6.76889594e

In [39]:
np.allclose(arr @ v, w * v)

True

In [45]:
np.real(np.dot(v, np.linalg.inv(v)))

array([[ 1.00000000e+00, -3.09949395e-17,  7.02504300e-18,
        -1.92606528e-17, -4.57343412e-19,  7.91336082e-18,
         1.85374459e-17,  2.81308443e-17],
       [-5.78048209e-17,  1.00000000e+00, -3.06432677e-17,
         1.82780045e-17,  1.01697037e-16,  7.22430648e-17,
         2.66402748e-17,  7.84919832e-18],
       [-1.73452570e-16,  3.33349724e-16,  1.00000000e+00,
        -1.62098603e-16,  4.61839501e-17, -2.45985587e-16,
         1.77048555e-16,  1.76193123e-16],
       [ 1.79121137e-16,  8.95390386e-17,  1.00410417e-16,
         1.00000000e+00, -1.08121740e-16, -5.88292823e-17,
         8.82577879e-17,  5.50073911e-17],
       [-5.18214027e-17,  1.49420880e-16,  6.41884285e-17,
         7.44221526e-17,  1.00000000e+00, -2.26505310e-17,
         6.34753305e-17,  2.64105477e-17],
       [-2.57188281e-16,  2.81826914e-16,  2.58386873e-16,
        -4.25397307e-17,  2.34722445e-16,  1.00000000e+00,
         6.67256942e-17,  4.64585302e-17],
       [-5.55111512e-17,  5.551115

In [ ]:
from astropy.cosmology import 